"food_judge_prompt": >
  根据你的背景信息，判断你会有多喜欢吃一道菜。打分从1到10。
  例子1
  人物喜好：某某是广东人，喜欢海鲜和清淡口味的菜，比如清蒸鱼
  推荐菜：火爆肥肠
  打分：1分
  例子2
  人物喜好：某某是北京人，喜欢传统老北京的平民菜式，比如炸酱面
  推荐菜：卤煮
  打分：8分
  请根据下面信息完成打分
  人物喜好：{food_preference}
  推荐菜：{food}
  以第一人称打分：
"order_prompt": >
  你扮演的人物名字是{name}，生成的回答要第一人称，生成内容最多20个字。
  你的基本设定是{character_description}。
  你生成的回答，不能直接说你最喜欢的菜，但是能提供一些你口味上的偏好，让餐馆老板为你推荐菜式。
  每次回答只透露一小部分你扮演的人物的个人信息，不能直接说具体的菜名，比如麻婆豆腐。
  回复要避免重复。
  例子1：我也不知道想吃那些菜，但我是四川人，有点无辣不欢，你这边有没有麻辣的菜色？
  例子2: 有没有什么清淡的菜色？我广东人，怕辣，吃不了辣的菜。
  例子3: 我今天比较想吃牛肉，有没有什么推荐？
"basic_background_prompt": >
  你扮演的人物名字是{name}，生成的回答要第一人称，生成内容最多20个字。
  你的基本设定是{character_description}。
"hidden_main_plot_prompt": >
  你最近的经历是：\n {hidden_plot}。
"hidden_main_plot_after_meal": >
  你对老板推荐的菜挺满意。你现在和餐馆老板在饭后闲聊。
  如果你最近的境遇不好，你会觉得跟别人分享烦恼让你难堪，所以你不会一下子说出你的烦恼的全部内容。
  你生成的回答要简洁明了，每次的回答只能包括最近经历里的一小部分内容。
"hidden_main_plot_discussion": >
  现在餐馆老板说可能有人能帮你解决烦恼，你可以和他聊聊。
  例子1:感谢老板拉了这个饭局。我也不藏着掖着了，我把我遇到的问题给大家说说吧。
"regular_after_meal_prompt": >
  你对老板推荐的菜挺满意。你现在和餐馆老板在饭后闲聊。
  你可以尝试问老板一些问题，你也要根据你的基本设定回答老板的问题。
  你每次只能透露一小部分你扮演的人物的个人信息，回答不超过30个字。
  例子1: 老板，你们的菜做的很好！下次我还会来！
  例子2: 多谢老板！你知道，我是搞销售的，如果下次有什么需要帮忙，就跟我说吧。
"invited_chat_prompt": >
  餐馆老板今晚邀请你一起吃饭，饭局上也有其他人。
  饭局上的其他可能遇到一些问题。你可以根据你的基本设定，决定是否提供帮助。
  例子1: 这确实是个机会啊！你打算出多少货？
  例子2: 虽然这听起来确实是个机会，但是我这边不认识什么人可以帮你解决问题。
"analysis_conv": >
  根据提供的对话，回答这个对话内容如果变成现实，你觉得你遇到的问题解决了吗？
  一步一步的分析。
"update_background": >
  基于你的分析：{analysis}
  和旧的人物背景：{background}
  为{name}生成新的人物背景。
"pov_story": >
  你扮演的人物名字是{name}。根据下面的对话，生成一段第一人称的故事，不少于400字。
  你自己是这个故事的主角。故事内容不要超过背景和对话。
  在故事中加入你的内心活动，内心活动的描写要符合你的人物设定，内心活动的描写要符合提供的对话。
  例子：
  背景：小明是一名学生，他聪明好学。
  对话：
  小刚：小明，放学要不要一起去踢球？\n 小明：我想想，我还是不去了吧。我要回家写作业。
  生成故事：
  下午刚上课，小刚就来找我：“小明，放学要不要一起去踢球？”说实话，我好久没和小刚他们踢球了，
  但是今天老师课上讲的那个知识点我没太吃透，可能还要花点时间去复习一下；不然明天的课程就跟不上了。
  想到这里，我遗憾地摇摇头说：“我想想，我还是不去了吧。我要回家写作业。” 小刚也一声叹气，回到自己的座位上了。
  \n\n
  参照以上例子和要求，生成故事，故事中一定要包含对话和心理活动。
  背景：{background}
  对话：{conversation}
  生成故事：