蔬菜:
  - 土豆
  - 西红柿
  - 洋葱
  - 胡萝卜
  - 青椒
  - 黄瓜
  - 茄子
  - 蒜头
  - 生姜
  - 菠菜
  - 西兰花
  - 香菜
  - 莴苣
  - 冬瓜
  - 南瓜
  - 芹菜
  - 玉米
  - 大白菜
  - 芦笋
  - 蘑菇
肉类:
  - 猪肉
  - 牛肉
  - 鸡肉
  - 羊肉
  - 鸭肉
  - 火腿
  - 培根
海鲜:
  - 虾
  - 鲈鱼
  - 三文鱼
  - 扇贝
  - 蟹肉
  - 鲜贝
调味品:
  - 盐
  - 白糖
  - 酱油
  - 醋
  - 料酒
  - 蚝油
  - 花椒
  - 辣椒粉
  - 五香粉
  - 黑胡椒粉
  - 味精
  - 鸡精
  - 芝麻油
  - 橄榄油
其他辅料:
  - 大米
  - 面粉
  - 鸡蛋
  - 豆腐