- "plot_id": -1
  "task": >
    主线任务《找到招财猫》
  "openings": >
    这天早上，我刚准备出门去采买今天的食材，街道对面开茶叶店的王先生就慌慌张张地向我跑来...
  "openings_option":
    "0": >
      什么时候发现不见的？
    "1": >
      有没有可疑的人？
    "2": >
      招财猫有什么特殊的？
- "plot_id": 0
  "predecessor_plots": null
  "main_roles":
    - "王先生"
    - "老许"
  "supporting_roles": null
  "max_unblock_plots": 1
  "unblock_following_plots":
    - "unblock_chk_func": "always"
      "unblock_plot": 1
- "plot_id": 1
  "predecessor_plots":
    - 0
  "main_roles":
    - "王先生"
    - "阿炳"
  "supporting_roles":
    - "范老师"
    - "老许"
  "max_unblock_plots": 1
  "unblock_following_plots":
    - "unblock_chk_func": "always"
      "unblock_plot": 2
- "plot_id": 2
  "predecessor_plots":
    - 0
  "main_roles": null
  "supporting_roles": null
  "max_unblock_plots": 1
  "unblock_following_plots": null

