- "plot_id": 1
  "predecessor_plots": null
  "main_roles":
    - "王先生"
    - "阿炳"
  "supporting_roles":
    - "老许"
    - "范老师"
  "max_unblock_plots": 1
  "unblock_following_plots":
    - "unblock_chk_func": "always"
      "unblock_plot": 2
  max_attempts: 2
  "plot_descriptions":
    "task": >
      找到招财猫
    "openings": >
      这天早上，我刚准备出门去采买今天的食材，街道对面开茶叶店的王先生就慌慌张张地向我跑来...
    "user_openings_option":
      "0": >
        什么时候发现不见的？
      "1": >
        有没有可疑的人？
      "2": >
        招财猫有什么特殊的？
    "npc_openings": >
      老板，我发现我的招财猫不见了！
    "npc_quit_openings": >
      哎，老板，反正你帮我打听打听吧！（说完，王先生就慌慌张张地跑开了）
    "done_condition": >
      你知道谁拿走了王先生的招财猫吗？正确邀请王先生和那个人，就能完成当前任务! 
      只有邀请王先生和那位真的拿走招财猫的角色（一共两个角色）才能算成功！
      邀请了除了这两人以外的角色，都会被判定为失败。
- "plot_id": 2
  "predecessor_plots":
    - 1
  "main_roles":
    - "王先生"
    - "老许"
  "supporting_roles": null
  "max_unblock_plots": 1
  "unblock_following_plots":
    - "unblock_chk_func": "always"
      "unblock_plot": 3
  "plot_descriptions":
    "task": >
      准备中。。。
    "openings": >
      准备中。。。
    "user_openings_option":
      "0": >
        准备中。。。
      "1": >
        准备中。。。
      "2": >
        准备中。。。
    "npc_openings": >
      准备中。。。
    "npc_quit_openings": >
      准备中。。。
- "plot_id": 3
  "predecessor_plots":
    - 2
  "main_roles": null
  "supporting_roles": null
  "max_unblock_plots": 1
  "unblock_following_plots": null
  "plot_descriptions":
    "task": >
      准备中。。。
    "openings": >
      准备中。。。
    "user_openings_option":
      "0": >
        准备中。。。
      "1": >
        准备中。。。
      "2": >
        准备中。。。
    "npc_openings": >
      准备中。。。
    "npc_quit_openings": >
      准备中。。。

