# -*- coding: utf-8 -*-
"""The goal pipeline class."""

from typing import AsyncGenerator

from pydantic import BaseModel, Field

from ..types import ReplyFinishedReason
from ..agent import Agent
from ..message import UserMsg, Msg, TextBlock, DataBlock
from ..event import (
    UserConfirmResultEvent,
    ExternalExecutionResultEvent,
    RequireExternalExecutionEvent,
    RequireUserConfirmEvent,
)


class _VerificationResult(BaseModel):
    """The result of a verification."""

    passed: bool = Field(
        description="Whether the verification passed or not.",
    )

    message: str = Field(
        description=(
            "If not passed, the message should explain why it "
            "failed, and what needs to be fixed."
        ),
    )


class GoalPipeline:
    """The goal pipeline class that run an executor and verifier in a loop
    until the goal is achieved."""

    def __init__(
        self,
        executor: Agent,
        verifier: Agent,
        goal: str | list[TextBlock | DataBlock],
        verifier_reset_context: bool = True,
        max_iters: int = 10,
    ) -> None:
        """Initialize the goal pipeline.

        Args:
            executor (`Agent`):
                The executor agent that performs the work.
            verifier (`Agent`):
                The verifier agent that checks the goal achievement.
            goal (`str | list[TextBlock | DataBlock]`):
                The goal that the executor should achieve.
            verifier_reset_context (`bool`, optional):
                Whether to reset the verifier's context after each iteration.
                Defaults to `False`.
            max_iters (`int`, optional):
                The maximum number of goal achievement attempts.
        """
        self.executor = executor
        self.verifier = verifier
        self.goal = goal
        self.verifier_reset_context = verifier_reset_context
        self.max_iters = max_iters
        # Rounds already judged. On the instance rather than in
        # ``reply_stream``, so a HITL resume does not restart the budget.
        self._iters = 0

    async def reply_stream(
        self,
        inputs: Msg
        | list[Msg]
        | UserConfirmResultEvent
        | ExternalExecutionResultEvent,
    ) -> AsyncGenerator:
        """Run the goal pipeline.

        Args:
            inputs (`Msg | list[Msg] | UserConfirmResultEvent | \
            ExternalExecutionResultEvent`):
                The inputs to the pipeline, which can be a message, a list of
                messages, a user confirmation result event, or an external
                execution result event.

        Yields:
            `AgentEvent`:
                The events generated by the executor and verifier agents
                during the pipeline execution.
        """

        executor_inputs, verifier_inputs = None, None
        if (
            isinstance(inputs, Msg)
            or isinstance(inputs, list)
            and all(isinstance(_, Msg) for _ in inputs)
        ):
            executor_inputs = inputs
            # A fresh run, so the iteration budget starts over.
            self._iters = 0

        elif isinstance(
            inputs,
            (UserConfirmResultEvent, ExternalExecutionResultEvent),
        ):
            if inputs.reply_id == self.executor.state.reply_id:
                executor_inputs = inputs
            elif inputs.reply_id == self.verifier.state.reply_id:
                verifier_inputs = inputs
            else:
                raise ValueError(
                    f"Invalid inputs with reply_id: {inputs.reply_id}. ",
                )

        while True:
            # Executor
            break_loop = False
            if executor_inputs is not None:
                # Run the executor with the given inputs
                async for _ in self.executor.reply_stream(
                    inputs=executor_inputs,
                ):
                    yield _
                    if isinstance(
                        _,
                        (
                            RequireExternalExecutionEvent,
                            RequireUserConfirmEvent,
                        ),
                    ):
                        break_loop = True

                if break_loop:
                    # Break the loop for hitl events
                    break

            # Verifier
            final_msg = None
            instruction = verifier_inputs or UserMsg(
                name="user",
                content=self.goal,
            )
            verifier_inputs = None
            while final_msg is None:
                async for _ in self.verifier.reply_stream(
                    inputs=instruction,
                    structured_schema=_VerificationResult,
                    yield_final_msg=True,
                ):
                    if (
                        isinstance(_, Msg)
                        and _.finished_reason == ReplyFinishedReason.COMPLETED
                    ):
                        final_msg = _
                    elif isinstance(
                        _,
                        (
                            RequireExternalExecutionEvent,
                            RequireUserConfirmEvent,
                        ),
                    ):
                        break_loop = True
                        yield _
                    else:
                        yield _

                if break_loop:
                    # Escape the loop for hitl events
                    break
                if final_msg is None:
                    continue
                if final_msg.structured_output is None:
                    # Update the instruction for valid verification result
                    # TODO: support multimodal verification instruction
                    final_msg = None
                    instruction = UserMsg(
                        name="system",
                        content=(
                            "<system-reminder>You have failed to "
                            "generate valid verification result. "
                            "You should call the "
                            "'GenerateStructuredOutput' tool with "
                            "a valid structured output that matches "
                            "the schema. Recall the verification "
                            "requirements as follows:\n"
                            f"{self.goal}</system-reminder>"
                        ),
                    )
                elif final_msg.structured_output.get("passed"):
                    # Verification passed, exit the loop
                    break_loop = True
                else:
                    self._iters += 1
                    if self._iters >= self.max_iters:
                        # Out of attempts; the work never passed
                        break_loop = True
                        break

                    # Feedback to the executor for further improvement
                    feedback = final_msg.structured_output.get("message")
                    executor_inputs = UserMsg(
                        name="system",
                        content=(
                            "<system-reminder>You've failed to pass the "
                            "verification. Now recorrect your work based on "
                            f"the following feedback:\n{feedback}"
                            "</system-reminder>"
                        ),
                    )

            if break_loop:
                # Break the loop for hitl events or verification passed
                break
