# -*- coding: utf-8 -*-
"""The judge module for tuner."""
from collections.abc import Awaitable, Callable
from pydantic import BaseModel, Field


class JudgeOutput(BaseModel):
    """The output of a judge function."""

    reward: float = Field(
        description="The reward value assigned by the judge function.",
    )

    metrics: dict[str, float] | None = Field(
        description="Metrics from the judge function.",
        default=None,
    )


JudgeType = Callable[..., Awaitable[JudgeOutput]]
# A judge function type for tuning.

# Args:
#     task (`dict`):
#         The task information for the corresponding workflow.
#     response (`Any`):
#         The response field of the WorkflowOutput generated by the
#         corresponding workflow.
#     auxiliary_models (`dict[str, ChatModelBase] | None`, optional):
#         A dictionary of additional chat models available for LLM-as-a-Judge
#         usage. The keys are model names, and the values are the corresponding
#         `ChatModelBase` instances.
#     logger (`Logger | None`, optional):
#         An optional logger for logging information during the judge
#         execution.
# Returns:
#     `JudgeOutput`:
#         The reward value assigned by the judge function along with optional
#         metrics.
