name: Pre-commit

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install AgentScope
      run: |
        pip install -q -e .[full]
    - name: Install pre-commit
      run: |
        pre-commit install
    - name: Pre-commit starts
      run: |
        pre-commit run --all-files > pre-commit.log 2>&1 || true
        cat pre-commit.log
        if grep -q Failed pre-commit.log; then
          echo -e "\e[41m  [**FAIL**] Please install pre-commit and format your code first. \e[0m"
          exit 1
        fi
        echo -e "\e[46m  ********************************Passed******************************** \e[0m"
    - name: Read report
      id: read_report
      run: |
        echo "PRE_COMMIT_REPORT<<EOF" >> $GITHUB_ENV
        cat pre-commit.log >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Comment PR with pre-commit.log
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Pre-commit
          ```plaintext
          ${{ env.PRE_COMMIT_REPORT }}
          ```